# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=24)),
                ('quiz_description', models.CharField(blank=True, max_length=512)),
                ('quiz_image', models.CharField(blank=True, max_length=512)),
                ('quiz_type', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
