# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170123_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_data',
            old_name='quiz_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quiz_data',
            old_name='quiz_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='quiz_data',
            name='quiz_image',
        ),
        migrations.AddField(
            model_name='quiz_data',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='quiz_image/'),
        ),
        migrations.AddField(
            model_name='quiz_data',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
