# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.IntegerField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.IntegerField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=512)),
                ('enrollmentNumber', models.PositiveSmallIntegerField(default=0)),
                ('rollNumber', models.PositiveSmallIntegerField(default=0)),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('mobile', models.PositiveSmallIntegerField(default=0)),
                ('email', models.CharField(max_length=120)),
                ('mobileVerified', models.BooleanField(default=False)),
                ('emailVerified', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Branch')),
                ('smester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Semester')),
            ],
        ),
    ]
