# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='rollNumber',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
