# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170311_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='enrollmentNumber',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mobile',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
